# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ayesh_pb2 as ayesh__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ayesh_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AyeshServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatStream = channel.stream_stream(
                '/ayesh.AyeshService/ChatStream',
                request_serializer=ayesh__pb2.ChatMessage.SerializeToString,
                response_deserializer=ayesh__pb2.ChatChunk.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/ayesh.AyeshService/Chat',
                request_serializer=ayesh__pb2.ChatRequest.SerializeToString,
                response_deserializer=ayesh__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/ayesh.AyeshService/ListFiles',
                request_serializer=ayesh__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=ayesh__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/ayesh.AyeshService/ReadFile',
                request_serializer=ayesh__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=ayesh__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/ayesh.AyeshService/WriteFile',
                request_serializer=ayesh__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=ayesh__pb2.WriteFileResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/ayesh.AyeshService/ListSessions',
                request_serializer=ayesh__pb2.Empty.SerializeToString,
                response_deserializer=ayesh__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/ayesh.AyeshService/GetSession',
                request_serializer=ayesh__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=ayesh__pb2.Session.FromString,
                _registered_method=True)
        self.ListSkills = channel.unary_unary(
                '/ayesh.AyeshService/ListSkills',
                request_serializer=ayesh__pb2.Empty.SerializeToString,
                response_deserializer=ayesh__pb2.ListSkillsResponse.FromString,
                _registered_method=True)
        self.InstallSkill = channel.unary_unary(
                '/ayesh.AyeshService/InstallSkill',
                request_serializer=ayesh__pb2.InstallSkillRequest.SerializeToString,
                response_deserializer=ayesh__pb2.Status.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/ayesh.AyeshService/GetConfig',
                request_serializer=ayesh__pb2.Empty.SerializeToString,
                response_deserializer=ayesh__pb2.Config.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/ayesh.AyeshService/SetConfig',
                request_serializer=ayesh__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=ayesh__pb2.Status.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ayesh.AyeshService/HealthCheck',
                request_serializer=ayesh__pb2.Empty.SerializeToString,
                response_deserializer=ayesh__pb2.HealthResponse.FromString,
                _registered_method=True)


class AyeshServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ChatStream(self, request_iterator, context):
        """Chat - bidirectional streaming untuk token-by-token response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Chat async - kirim pesan, dapatkan response sekali
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """File operations - unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Sessions - unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSkills(self, request, context):
        """Skills - unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallSkill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Config - unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health - unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AyeshServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=ayesh__pb2.ChatMessage.FromString,
                    response_serializer=ayesh__pb2.ChatChunk.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=ayesh__pb2.ChatRequest.FromString,
                    response_serializer=ayesh__pb2.ChatResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=ayesh__pb2.ListFilesRequest.FromString,
                    response_serializer=ayesh__pb2.ListFilesResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=ayesh__pb2.ReadFileRequest.FromString,
                    response_serializer=ayesh__pb2.ReadFileResponse.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=ayesh__pb2.WriteFileRequest.FromString,
                    response_serializer=ayesh__pb2.WriteFileResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=ayesh__pb2.Empty.FromString,
                    response_serializer=ayesh__pb2.ListSessionsResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=ayesh__pb2.GetSessionRequest.FromString,
                    response_serializer=ayesh__pb2.Session.SerializeToString,
            ),
            'ListSkills': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSkills,
                    request_deserializer=ayesh__pb2.Empty.FromString,
                    response_serializer=ayesh__pb2.ListSkillsResponse.SerializeToString,
            ),
            'InstallSkill': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallSkill,
                    request_deserializer=ayesh__pb2.InstallSkillRequest.FromString,
                    response_serializer=ayesh__pb2.Status.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=ayesh__pb2.Empty.FromString,
                    response_serializer=ayesh__pb2.Config.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=ayesh__pb2.SetConfigRequest.FromString,
                    response_serializer=ayesh__pb2.Status.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ayesh__pb2.Empty.FromString,
                    response_serializer=ayesh__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ayesh.AyeshService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ayesh.AyeshService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AyeshService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ayesh.AyeshService/ChatStream',
            ayesh__pb2.ChatMessage.SerializeToString,
            ayesh__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ayesh.AyeshService/Chat',
            ayesh__pb2.ChatRequest.SerializeToString,
            ayesh__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ayesh.AyeshService/ListFiles',
            ayesh__pb2.ListFilesRequest.SerializeToString,
            ayesh__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ayesh.AyeshService/ReadFile',
            ayesh__pb2.ReadFileRequest.SerializeToString,
            ayesh__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ayesh.AyeshService/WriteFile',
            ayesh__pb2.WriteFileRequest.SerializeToString,
            ayesh__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ayesh.AyeshService/ListSessions',
            ayesh__pb2.Empty.SerializeToString,
            ayesh__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ayesh.AyeshService/GetSession',
            ayesh__pb2.GetSessionRequest.SerializeToString,
            ayesh__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSkills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ayesh.AyeshService/ListSkills',
            ayesh__pb2.Empty.SerializeToString,
            ayesh__pb2.ListSkillsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallSkill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ayesh.AyeshService/InstallSkill',
            ayesh__pb2.InstallSkillRequest.SerializeToString,
            ayesh__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ayesh.AyeshService/GetConfig',
            ayesh__pb2.Empty.SerializeToString,
            ayesh__pb2.Config.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ayesh.AyeshService/SetConfig',
            ayesh__pb2.SetConfigRequest.SerializeToString,
            ayesh__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ayesh.AyeshService/HealthCheck',
            ayesh__pb2.Empty.SerializeToString,
            ayesh__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
