"""Multi-user + API keys with RBAC — re-export layer.

- users: id, name, key_hash (salt$sha256), prefix, role (owner|vip|user), active.
  vip = paid tier $13.87 via webhook; user/vip hanya self-data, owner = global.
- Auth: header X-API-Key atau Authorization: Bearer. Default REQUIRE_API_KEY=1 (fail-closed).
  Bila REQUIRE_API_KEY=0, chat boleh anonim tapi control-plane tetap fail-closed.
- RBAC roles:
  owner: full (users, keywords, templates, marketplace, audit, analytics, vip manage)
  vip:   paid user — same API as user, higher quota + premium models
  user:  chat, own sessions/memory/tasks/plans, own llm/mcp/skill configs
"""

# ── Re-export all public symbols from submodules ───────────────────────
from src.core.auth.auth_context import (
    UserLLMConfig,
    _authenticated,
    _utcnow,
    current_user,
    current_user_llm_config,
    current_user_role,
    get_current_user,
    get_current_user_id,
    get_current_user_llm_config,
    get_current_user_role,
    is_authenticated,
    set_current_user,
    set_current_user_llm_config,
    set_current_user_role,
)
from src.core.auth.auth_guards import (
    bootstrap_owner,
    require_admin,
    require_auth,
    require_authenticated,
    require_owner,
    require_owner_only,
    require_owner_or_admin,
    require_self_or_owner,
    require_vip,
)
from src.core.auth.auth_keys import (
    _ensure_rotation_columns,
    _ensure_user_config_tables,
    _ensure_vip_columns,
    _ensure_vip_tables,
    _hash_key,
    add_user_llm_config,
    create_user,
    deactivate_user,
    delete_user_llm_config,
    demote_user_vip,
    get_user_by_id,
    get_user_default_llm,
    invalidate_user_cache,
    is_mcp_enabled_for_user,
    is_skill_enabled_for_user,
    list_user_llm_configs,
    list_user_mcp_overrides,
    list_user_skill_overrides,
    list_users,
    rotate_user_key,
    set_user_mcp_override,
    set_user_skill_override,
    set_user_vip,
    update_user_llm_config_entry,
    verify_key,
)
from src.core.auth.auth_request import bind_request_user

__all__ = [
    "UserLLMConfig",
    "_authenticated",
    "_ensure_rotation_columns",
    "_ensure_user_config_tables",
    "_ensure_vip_columns",
    "_ensure_vip_tables",
    "_hash_key",
    "_utcnow",
    "add_user_llm_config",
    "bind_request_user",
    "bootstrap_owner",
    "create_user",
    "current_user",
    "current_user_llm_config",
    "current_user_role",
    "deactivate_user",
    "delete_user_llm_config",
    "demote_user_vip",
    "get_current_user",
    "get_current_user_id",
    "get_current_user_llm_config",
    "get_current_user_role",
    "get_user_by_id",
    "get_user_default_llm",
    "invalidate_user_cache",
    "is_authenticated",
    "is_mcp_enabled_for_user",
    "is_skill_enabled_for_user",
    "list_user_llm_configs",
    "list_user_mcp_overrides",
    "list_user_skill_overrides",
    "list_users",
    "require_admin",
    "require_auth",
    "require_authenticated",
    "require_owner",
    "require_owner_only",
    "require_owner_or_admin",
    "require_self_or_owner",
    "require_vip",
    "rotate_user_key",
    "set_current_user",
    "set_current_user_llm_config",
    "set_current_user_role",
    "set_user_mcp_override",
    "set_user_skill_override",
    "set_user_vip",
    "update_user_llm_config_entry",
    "verify_key",
]
