"""Multi-user + API keys with RBAC — re-export layer.

- users: id, name, key_hash (salt$sha256), prefix, role (owner|vip|user), active.
  vip = paid tier $13.87 via webhook; user/vip hanya self-data, owner = global.
- Auth: header X-API-Key atau Authorization: Bearer. Default REQUIRE_API_KEY=1 (fail-closed).
  Bila REQUIRE_API_KEY=0, chat boleh anonim tapi control-plane tetap fail-closed.
- RBAC roles:
  owner: full (users, keywords, templates, marketplace, audit, analytics, vip manage)
  vip:   paid user — same API as user, higher quota + premium models
  user:  chat, own sessions/memory/tasks/plans, own llm/mcp/skill configs
"""

# ── Re-export all public symbols from submodules ───────────────────────
from src.core.auth.account import (
    EmailAlreadyRegistered,
    authenticate_password,
    change_user_password,
    confirm_email_verification,
    confirm_password_reset,
    confirm_totp,
    disable_totp,
    enable_totp,
    get_account,
    get_user_by_username,
    is_valid_username,
    issue_2fa_challenge,
    issue_password_reset,
    link_oauth_identity,
    normalize_username,
    register_with_password,
    resend_verification,
    resolve_2fa_challenge,
    verify_user_totp,
)
from src.core.auth.auth_context import (
    UserLLMConfig,
    _authenticated,
    _utcnow,
    current_user,
    current_user_llm_config,
    current_user_role,
    get_current_user,
    get_current_user_id,
    get_current_user_llm_config,
    get_current_user_role,
    is_authenticated,
    set_current_user,
    set_current_user_llm_config,
    set_current_user_role,
)
from src.core.auth.auth_guards import (
    bootstrap_owner,
    require_admin,
    require_auth,
    require_authenticated,
    require_owner,
    require_owner_only,
    require_owner_or_admin,
    require_self_or_owner,
    require_vip,
)
from src.core.auth.auth_keys import (
    _ensure_rotation_columns,
    _ensure_user_config_tables,
    _ensure_vip_columns,
    _ensure_vip_tables,
    _hash_key,
    add_user_llm_config,
    create_user,
    deactivate_user,
    delete_user_llm_config,
    demote_user_vip,
    get_user_by_id,
    get_user_default_llm,
    invalidate_user_cache,
    is_mcp_enabled_for_user,
    is_skill_enabled_for_user,
    list_user_llm_configs,
    list_user_mcp_overrides,
    list_user_skill_overrides,
    list_users,
    rotate_user_key,
    set_user_mcp_override,
    set_user_skill_override,
    set_user_vip,
    update_user_llm_config_entry,
    verify_key,
)
from src.core.auth.auth_request import bind_request_user
from src.core.auth.emailer import email_enabled, send_email
from src.core.auth.oauth import exchange_oauth, is_provider_enabled, start_oauth
from src.core.auth.passwords import hash_password, password_policy_ok, verify_password
from src.core.auth.sessions import (
    clear_session_cookies,
    create_session,
    read_session_token,
    revoke_all_user_sessions,
    revoke_session,
    set_session_cookie,
    verify_csrf,
    verify_session,
)
from src.core.auth.totp import generate_backup_codes, generate_totp_secret, totp_uri, verify_backup_code, verify_totp

__all__ = [
    "EmailAlreadyRegistered",
    "UserLLMConfig",
    "_authenticated",
    "_ensure_rotation_columns",
    "_ensure_user_config_tables",
    "_ensure_vip_columns",
    "_ensure_vip_tables",
    "_hash_key",
    "_utcnow",
    "add_user_llm_config",
    "authenticate_password",
    "bind_request_user",
    "bootstrap_owner",
    "change_user_password",
    "clear_session_cookies",
    "confirm_email_verification",
    "confirm_password_reset",
    "confirm_totp",
    "create_session",
    "create_user",
    "current_user",
    "current_user_llm_config",
    "current_user_role",
    "deactivate_user",
    "delete_user_llm_config",
    "demote_user_vip",
    "disable_totp",
    "email_enabled",
    "enable_totp",
    "exchange_oauth",
    "generate_backup_codes",
    "generate_totp_secret",
    "get_account",
    "get_current_user",
    "get_current_user_id",
    "get_current_user_llm_config",
    "get_current_user_role",
    "get_user_by_id",
    "get_user_by_username",
    "get_user_default_llm",
    "hash_password",
    "invalidate_user_cache",
    "is_authenticated",
    "is_mcp_enabled_for_user",
    "is_provider_enabled",
    "is_skill_enabled_for_user",
    "is_valid_username",
    "issue_2fa_challenge",
    "issue_password_reset",
    "link_oauth_identity",
    "list_user_llm_configs",
    "list_user_mcp_overrides",
    "list_user_skill_overrides",
    "list_users",
    "normalize_username",
    "password_policy_ok",
    "read_session_token",
    "register_with_password",
    "require_admin",
    "require_auth",
    "require_authenticated",
    "require_owner",
    "require_owner_only",
    "require_owner_or_admin",
    "require_self_or_owner",
    "require_vip",
    "resend_verification",
    "resolve_2fa_challenge",
    "revoke_all_user_sessions",
    "revoke_session",
    "rotate_user_key",
    "send_email",
    "set_current_user",
    "set_current_user_llm_config",
    "set_current_user_role",
    "set_session_cookie",
    "set_user_mcp_override",
    "set_user_skill_override",
    "set_user_vip",
    "start_oauth",
    "totp_uri",
    "update_user_llm_config_entry",
    "verify_backup_code",
    "verify_csrf",
    "verify_key",
    "verify_password",
    "verify_session",
    "verify_totp",
    "verify_user_totp",
]
